mybatis.configuration.map-underscore-to-camel-case: true
mybatis.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server.tomcat.uri-encoding: UTF-8

logback.level: info
spring.application.name: client
spring.session.store-type: none
spring.http.encoding.force: true
spring.http.encoding.charset: UTF-8
spring.http.encoding.enabled: true

server.port: 9010

#邮箱
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.properties.mail.smtp.starttls.required: true
spring.mail.properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
spring.mail.properties.content.admin.subject: 零创世界验证码
spring.mail.properties.content.admin.text: 您的验证码是${captcha}，5分钟后过期，千万别告诉别人哦！
spring.mail.host: smtp.mxhichina.com
spring.mail.port: 465
spring.mail.username: zero@yanhuada.cn
spring.mail.password: YANhuada187188

# 配置redis缓存
spring.redis.database: 5
spring.redis.host: 120.79.174.111
spring.redis.port: 6379
spring.redis.password: yan187188
## 配置数据库
spring.datasource.url: jdbc:mysql://120.79.174.111:3306/zero
spring.datasource.username: root
spring.datasource.password: YANhuada187188?
spring.datasource.driverClassName: com.mysql.jdbc.Driver

# jwt
jwt.rsa.private-key: test_private_key.der
jwt.rsa.public-key: test_public_key.der

aliyun.access-key-id: LTAI4FdqSN5G7UVNa1qmszYC
aliyun.access-key-secret: YtOEMsTYiuZhQu6iQUDSEn76WlENtG
aliyun.role-arn: acs:ram::1444616359399460:role/oss
aliyun.role-session-name: develop
aliyun.sts-endpoint: sts.cn-shenzhen.aliyuncs.com
aliyun.sms-region-id: cn-hangzhou
aliyun.sms-sign-name: 零创世界
aliyun.sms-template-code: SMS_184616283

wechat.miniapp.appid: wx7ae3ec69e0a076ae
wechat.miniapp.secret: 4006a700e4e701ea40d810673fdf5918
